
package trainservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TrainPortType", targetNamespace = "http://mohamed.nl/treinservice/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrainPortType {


    /**
     * 
     * @param station
     * @return
     *     returns int
     * @throws GetTotalRidesError
     */
    @WebMethod(action = "getTotalRides")
    @WebResult(name = "totalrides", targetNamespace = "http://mohamed.nl/treinservice/response/", partName = "total")
    public int getTotalRides(
        @WebParam(name = "station", targetNamespace = "http://mohamed.nl/treinservice/request/", partName = "station")
        String station)
        throws GetTotalRidesError
    ;

    /**
     * 
     * @param station
     * @return
     *     returns int
     * @throws GetTotalEnergyConsumptionError
     */
    @WebMethod(action = "getTotalEnergyConsumption")
    @WebResult(name = "energy", targetNamespace = "http://mohamed.nl/treinservice/response/", partName = "total-energy")
    public int getTotalEnergyConsumption(
        @WebParam(name = "station", targetNamespace = "http://mohamed.nl/treinservice/request/", partName = "station")
        String station)
        throws GetTotalEnergyConsumptionError
    ;

    /**
     * 
     * @param station
     * @return
     *     returns int
     * @throws GetTotalEnergyConsumptionPerHourError
     */
    @WebMethod(action = "getTotalEnergyConsumptionPerHour")
    @WebResult(name = "energy", targetNamespace = "http://mohamed.nl/treinservice/response/", partName = "energy-per-hour")
    public int getTotalEnergyConsumptionPerHour(
        @WebParam(name = "station", targetNamespace = "http://mohamed.nl/treinservice/request/", partName = "station")
        String station)
        throws GetTotalEnergyConsumptionPerHourError
    ;

    /**
     * 
     * @param station
     * @return
     *     returns int
     * @throws GetTotalEnergyConsumptionHourError
     */
    @WebMethod(action = "getTotalEnergyConsumptionHour")
    @WebResult(name = "energy", targetNamespace = "http://mohamed.nl/treinservice/response/", partName = "energy-per-hour")
    public int getTotalEnergyConsumptionHour(
        @WebParam(name = "station-hours", targetNamespace = "http://mohamed.nl/treinservice/request/", partName = "station")
        StationHours station)
        throws GetTotalEnergyConsumptionHourError
    ;

    /**
     * 
     * @param station
     * @return
     *     returns java.lang.String
     * @throws GetAllRidesError
     */
    @WebMethod(action = "getAllRides")
    @WebResult(name = "rides", targetNamespace = "http://mohamed.nl/treinservice/response/", partName = "stations")
    public String getAllRides(
        @WebParam(name = "station", targetNamespace = "http://mohamed.nl/treinservice/request/", partName = "station")
        String station)
        throws GetAllRidesError
    ;

    /**
     * 
     * @param station
     * @return
     *     returns java.lang.String
     * @throws GetStationedTrainsError
     */
    @WebMethod(action = "getStationedTrains")
    @WebResult(name = "stationed-trains", targetNamespace = "http://mohamed.nl/treinservice/response/", partName = "stationed-trains")
    public String getStationedTrains(
        @WebParam(name = "station", targetNamespace = "http://mohamed.nl/treinservice/request/", partName = "station")
        String station)
        throws GetStationedTrainsError
    ;

}
